-- OBJETIVO DO SCRIPT: Implementa a responsabilidade definida pelo arquivo V1__operacao_base.sql.
-- Cada bloco descreve a estrutura ou os dados que serão criados no banco.
-- Estrutura inicial PostgreSQL migrada do legado Oracle/APEX do SIGACrim.
-- Mantém nomes de tabelas e colunas do legado para facilitar a futura carga.
-- Constraints e índices seguem padrão único do novo projeto.

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_etapa_operacao
(
    id_etapa_operacao bigint generated by default as identity,
    cd_etapa_operacao varchar(255) not null,
    ds_etapa_operacao varchar(255) not null,
    ob_etapa_operacao varchar(2000),
    ds_cor_etapa varchar(20),

    constraint pk_tb_etapa_operacao
        primary key (id_etapa_operacao),

    constraint uk_tb_etapa_operacao__cd_etapa_operacao
        unique (cd_etapa_operacao)
);

-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_etapa_operacao__ds_etapa_operacao
    on tb_etapa_operacao (ds_etapa_operacao);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_visibilidade
(
    id_visibilidade varchar(1),
    ds_visibilidade varchar(60),

    constraint pk_tb_visibilidade
        primary key (id_visibilidade)
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_operacao
(
    id_operacao bigint generated by default as identity,
    id_operacao_relacionada_fk bigint,
    id_etapa_operacao_fk bigint default 10,
    id_visibilidade_fk varchar(1) not null,
    nr_inquerito_ipl varchar(12),
    no_operacao varchar(255) not null,
    ds_razao_nome varchar(1000),
    dt_inicio_operacao date,
    st_tem_operacao_anterior varchar(1),
    st_abortada varchar(1),
    st_validacao varchar(1),
    st_finalizacao varchar(1),
    st_homologacao varchar(1),
    st_concluida varchar(1),
    ob_abortada varchar(2000),
    ob_validacao varchar(2000),
    ob_finalizacao varchar(2000),
    ob_homologacao varchar(2000),
    ob_rejeicao varchar(2000),
    st_validacao_abort varchar(1),
    ob_validacao_abort varchar(2000),
    ds_operacao varchar(2000),
    st_username_validacao varchar(255),
    st_username_homologacao varchar(255),
    dt_validacao timestamp without time zone,
    dt_homologacao timestamp without time zone,
    dt_cadastro timestamp without time zone default current_timestamp,
    dt_ultima_alteracao timestamp without time zone default current_timestamp,
    st_username_ultima_alteracao varchar(255),
    st_username_cadastro varchar(255),
    ds_ultima_alteracao varchar(255),
    st_setorial_saved smallint,
    ds_uf_inq_out varchar(1000),
    ds_unidade_inq_out varchar(1000),
    ds_area_inq_out varchar(1000),
    st_andamento_saved integer,
    st_pre_deflagracao_saved smallint,
    st_deflagracao_saved smallint,
    ds_etapa_operacao_out varchar(255),
    ds_notas varchar(4000),
    dt_cache_update timestamp without time zone,
    ds_cache_return varchar(1000),
    nr_inquerito_ipl_backup varchar(40),
    st_system integer,

    constraint pk_tb_operacao
        primary key (id_operacao),

    constraint fk_tb_operacao__tb_etapa_operacao
        foreign key (id_etapa_operacao_fk)
        references tb_etapa_operacao (id_etapa_operacao),

    constraint fk_tb_operacao__tb_visibilidade
        foreign key (id_visibilidade_fk)
        references tb_visibilidade (id_visibilidade),

    constraint fk_tb_operacao__tb_operacao_relacionada
        foreign key (id_operacao_relacionada_fk)
        references tb_operacao (id_operacao),

    constraint ck_tb_operacao__st_tem_operacao_anterior
        check (
            st_tem_operacao_anterior is null
            or st_tem_operacao_anterior in ('0', '1')
        )
);

-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_operacao__no_operacao
    on tb_operacao (no_operacao);

-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_operacao__id_etapa_operacao_fk
    on tb_operacao (id_etapa_operacao_fk);

-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_operacao__nr_inquerito_ipl
    on tb_operacao (nr_inquerito_ipl);

-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_operacao__dt_ultima_alteracao
    on tb_operacao (dt_ultima_alteracao);

-- Registro inicial compatível com o default 10 existente no legado.
-- Insere um registro inicial necessário para o funcionamento do sistema.
insert into tb_etapa_operacao
    (id_etapa_operacao, cd_etapa_operacao, ds_etapa_operacao, ob_etapa_operacao, ds_cor_etapa)
values
    (10, 'cadastro', 'Cadastro', 'Operação em cadastramento.', '#2563eb');

select setval(
    pg_get_serial_sequence('tb_etapa_operacao', 'id_etapa_operacao'),
    (select max(id_etapa_operacao) from tb_etapa_operacao)
);

-- Insere um registro inicial necessário para o funcionamento do sistema.
insert into tb_visibilidade (id_visibilidade, ds_visibilidade)
values
    ('R', 'Restrita'),
    ('P', 'Pública');


-- -----------------------------------------------------------------------------
-- Usuários e escopo organizacional
-- Modelo normalizado do legado APEX: usuário pode possuir vários perfis, UFs,
-- áreas de atribuição e unidades.
-- -----------------------------------------------------------------------------

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_uf
(
    id_uf bigint generated by default as identity,
    cd_uf integer not null,
    sg_uf varchar(2) not null,
    no_uf varchar(60) not null,
    st_ativo varchar(1) not null default '1',

    constraint pk_tb_uf primary key (id_uf),
    constraint uk_tb_uf__cd_uf unique (cd_uf),
    constraint uk_tb_uf__sg_uf unique (sg_uf),
    constraint ck_tb_uf__st_ativo check (st_ativo in ('0','1'))
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_unidade
(
    id_unidade bigint generated by default as identity,
    cd_unidade_epol bigint,
    sg_unidade varchar(50) not null,
    no_unidade varchar(255) not null,
    id_uf_fk bigint,
    cd_siorg_unidade bigint,
    st_fronteira varchar(1),
    st_ativo varchar(1) not null default '1',

    constraint pk_tb_unidade primary key (id_unidade),
    constraint uk_tb_unidade__cd_unidade_epol unique (cd_unidade_epol),
    constraint uk_tb_unidade__sg_unidade unique (sg_unidade),
    constraint fk_tb_unidade__tb_uf foreign key (id_uf_fk) references tb_uf (id_uf),
    constraint ck_tb_unidade__st_fronteira check (st_fronteira is null or st_fronteira in ('0','1')),
    constraint ck_tb_unidade__st_ativo check (st_ativo in ('0','1'))
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_area_atribuicao
(
    id_area_atribuicao bigint generated by default as identity,
    cd_area_atribuicao_epol bigint,
    no_area_atribuicao varchar(200) not null,
    id_unidade_fk bigint,
    st_ativo varchar(1) not null default '1',

    constraint pk_tb_area_atribuicao primary key (id_area_atribuicao),
    constraint uk_tb_area_atribuicao__cd_epol unique (cd_area_atribuicao_epol),
    constraint fk_tb_area_atribuicao__tb_unidade foreign key (id_unidade_fk) references tb_unidade (id_unidade),
    constraint ck_tb_area_atribuicao__st_ativo check (st_ativo in ('0','1'))
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_perfil
(
    id_perfil bigint generated by default as identity,
    cd_perfil varchar(60) not null,
    no_perfil varchar(120) not null,
    ds_perfil varchar(500),
    st_ativo varchar(1) not null default '1',

    constraint pk_tb_perfil primary key (id_perfil),
    constraint uk_tb_perfil__cd_perfil unique (cd_perfil),
    constraint ck_tb_perfil__st_ativo check (st_ativo in ('0','1'))
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_usuario
(
    id_usuario bigint generated by default as identity,
    cd_usuario varchar(255) not null,
    no_usuario varchar(255) not null,
    ds_email varchar(255),
    ds_senha_hash varchar(255) not null,
    st_ativo varchar(1) not null default '1',
    st_trocar_senha varchar(1) not null default '1',
    st_suporte varchar(1) not null default '0',
    dt_cadastro timestamp without time zone not null default current_timestamp,
    dt_ultima_alteracao timestamp without time zone not null default current_timestamp,
    dt_primeiro_acesso timestamp without time zone,
    dt_ultimo_acesso timestamp without time zone,

    constraint pk_tb_usuario primary key (id_usuario),
    constraint uk_tb_usuario__cd_usuario unique (cd_usuario),
    constraint uk_tb_usuario__ds_email unique (ds_email),
    constraint ck_tb_usuario__st_ativo check (st_ativo in ('0','1')),
    constraint ck_tb_usuario__st_trocar_senha check (st_trocar_senha in ('0','1')),
    constraint ck_tb_usuario__st_suporte check (st_suporte in ('0','1'))
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_usuario_perfil
(
    id_usuario_fk bigint not null,
    id_perfil_fk bigint not null,
    dt_cadastro timestamp without time zone not null default current_timestamp,
    constraint pk_tb_usuario_perfil primary key (id_usuario_fk, id_perfil_fk),
    constraint fk_tb_usuario_perfil__tb_usuario foreign key (id_usuario_fk) references tb_usuario (id_usuario) on delete cascade,
    constraint fk_tb_usuario_perfil__tb_perfil foreign key (id_perfil_fk) references tb_perfil (id_perfil)
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_usuario_uf
(
    id_usuario_fk bigint not null,
    id_uf_fk bigint not null,
    constraint pk_tb_usuario_uf primary key (id_usuario_fk, id_uf_fk),
    constraint fk_tb_usuario_uf__tb_usuario foreign key (id_usuario_fk) references tb_usuario (id_usuario) on delete cascade,
    constraint fk_tb_usuario_uf__tb_uf foreign key (id_uf_fk) references tb_uf (id_uf)
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_usuario_area_atribuicao
(
    id_usuario_fk bigint not null,
    id_area_atribuicao_fk bigint not null,
    constraint pk_tb_usuario_area_atribuicao primary key (id_usuario_fk, id_area_atribuicao_fk),
    constraint fk_tb_usuario_area__tb_usuario foreign key (id_usuario_fk) references tb_usuario (id_usuario) on delete cascade,
    constraint fk_tb_usuario_area__tb_area foreign key (id_area_atribuicao_fk) references tb_area_atribuicao (id_area_atribuicao)
);

-- Cria a tabela e define as colunas persistidas por este domínio.
create table tb_usuario_unidade
(
    id_usuario_fk bigint not null,
    id_unidade_fk bigint not null,
    constraint pk_tb_usuario_unidade primary key (id_usuario_fk, id_unidade_fk),
    constraint fk_tb_usuario_unidade__tb_usuario foreign key (id_usuario_fk) references tb_usuario (id_usuario) on delete cascade,
    constraint fk_tb_usuario_unidade__tb_unidade foreign key (id_unidade_fk) references tb_unidade (id_unidade)
);

-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_usuario__no_usuario on tb_usuario (no_usuario);
-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_usuario__ds_email on tb_usuario (ds_email);
-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_unidade__id_uf_fk on tb_unidade (id_uf_fk);
-- Cria um índice para acelerar consultas ou garantir unicidade.
create index ix_tb_area_atribuicao__id_unidade_fk on tb_area_atribuicao (id_unidade_fk);

-- Perfis e usuário inicial do ambiente local.
-- Esta é a carga inicial única da V1 para um banco vazio.
-- Insere um registro inicial necessário para o funcionamento do sistema.
insert into tb_perfil (cd_perfil, no_perfil, ds_perfil)
values
    ('administrador', 'Administrador', 'Acesso administrativo ao SIGACrim'),
    ('gestor', 'Gestor', 'Gestão de operações e eventos'),
    ('usuario', 'Usuário', 'Acesso operacional básico');

-- Insere um registro inicial necessário para o funcionamento do sistema.
insert into tb_usuario
    (cd_usuario, no_usuario, ds_email, ds_senha_hash, st_ativo, st_trocar_senha, st_suporte)
values
    ('admin', 'Administrador Local', 'admin@sigacrim.local', '$2y$10$LbkIZGEJm1vMS4UGDHk.F.DcSVZBjAsl3Z86jUjCKx2s0jrSu.67K', '1', '1', '1');

-- Insere um registro inicial necessário para o funcionamento do sistema.
insert into tb_usuario_perfil (id_usuario_fk, id_perfil_fk)
select u.id_usuario, p.id_perfil
from tb_usuario u
join tb_perfil p on p.cd_perfil = 'administrador'
where u.cd_usuario = 'admin';
