-- Estrutura inicial PostgreSQL migrada do legado Oracle/APEX do SIGACrim.
-- Mantém nomes de tabelas e colunas do legado para facilitar a futura carga.
-- Constraints e índices seguem padrão único do novo projeto.

create table tb_etapa_operacao
(
    id_etapa_operacao bigint generated by default as identity,
    cd_etapa_operacao varchar(255) not null,
    ds_etapa_operacao varchar(255) not null,
    ob_etapa_operacao varchar(2000),
    ds_cor_etapa varchar(20),

    constraint pk_tb_etapa_operacao
        primary key (id_etapa_operacao),

    constraint uk_tb_etapa_operacao__cd_etapa_operacao
        unique (cd_etapa_operacao)
);

create index ix_tb_etapa_operacao__ds_etapa_operacao
    on tb_etapa_operacao (ds_etapa_operacao);

create table tb_visibilidade
(
    id_visibilidade char(1),
    ds_visibilidade varchar(60),

    constraint pk_tb_visibilidade
        primary key (id_visibilidade)
);

create table tb_operacao
(
    id_operacao bigint generated by default as identity,
    id_operacao_relacionada_fk bigint,
    id_etapa_operacao_fk bigint default 10,
    id_visibilidade_fk char(1) not null,
    nr_inquerito_ipl varchar(12),
    no_operacao varchar(255) not null,
    ds_razao_nome varchar(1000),
    dt_inicio_operacao date,
    st_tem_operacao_anterior char(1),
    st_abortada char(1),
    st_validacao char(1),
    st_finalizacao char(1),
    st_homologacao char(1),
    st_concluida char(1),
    ob_abortada varchar(2000),
    ob_validacao varchar(2000),
    ob_finalizacao varchar(2000),
    ob_homologacao varchar(2000),
    ob_rejeicao varchar(2000),
    st_validacao_abort char(1),
    ob_validacao_abort varchar(2000),
    ds_operacao varchar(2000),
    st_username_validacao varchar(255),
    st_username_homologacao varchar(255),
    dt_validacao timestamp without time zone,
    dt_homologacao timestamp without time zone,
    dt_cadastro timestamp without time zone default current_timestamp,
    dt_ultima_alteracao timestamp without time zone default current_timestamp,
    st_username_ultima_alteracao varchar(255),
    st_username_cadastro varchar(255),
    ds_ultima_alteracao varchar(255),
    st_setorial_saved smallint,
    ds_uf_inq_out varchar(1000),
    ds_unidade_inq_out varchar(1000),
    ds_area_inq_out varchar(1000),
    st_andamento_saved integer,
    st_pre_deflagracao_saved smallint,
    st_deflagracao_saved smallint,
    ds_etapa_operacao_out varchar(255),
    ds_notas varchar(4000),
    dt_cache_update timestamp without time zone,
    ds_cache_return varchar(1000),
    nr_inquerito_ipl_backup varchar(40),
    st_system integer,

    constraint pk_tb_operacao
        primary key (id_operacao),

    constraint fk_tb_operacao__tb_etapa_operacao
        foreign key (id_etapa_operacao_fk)
        references tb_etapa_operacao (id_etapa_operacao),

    constraint fk_tb_operacao__tb_visibilidade
        foreign key (id_visibilidade_fk)
        references tb_visibilidade (id_visibilidade),

    constraint fk_tb_operacao__tb_operacao_relacionada
        foreign key (id_operacao_relacionada_fk)
        references tb_operacao (id_operacao),

    constraint ck_tb_operacao__st_tem_operacao_anterior
        check (
            st_tem_operacao_anterior is null
            or st_tem_operacao_anterior in ('0', '1')
        )
);

create index ix_tb_operacao__no_operacao
    on tb_operacao (no_operacao);

create index ix_tb_operacao__id_etapa_operacao_fk
    on tb_operacao (id_etapa_operacao_fk);

create index ix_tb_operacao__nr_inquerito_ipl
    on tb_operacao (nr_inquerito_ipl);

create index ix_tb_operacao__dt_ultima_alteracao
    on tb_operacao (dt_ultima_alteracao);

-- Registro inicial compatível com o default 10 existente no legado.
insert into tb_etapa_operacao
    (id_etapa_operacao, cd_etapa_operacao, ds_etapa_operacao, ob_etapa_operacao, ds_cor_etapa)
values
    (10, 'cadastro', 'Cadastro', 'Operação em cadastramento.', '#2563eb');

select setval(
    pg_get_serial_sequence('tb_etapa_operacao', 'id_etapa_operacao'),
    (select max(id_etapa_operacao) from tb_etapa_operacao)
);

insert into tb_visibilidade (id_visibilidade, ds_visibilidade)
values
    ('R', 'Restrita'),
    ('P', 'Pública');
